public enum ChampionEnum
{
    Sylas,
    Seraphine,
    KogMaw,
    Poppy,
    Vi,
    Morgana,
    Jax,
    Alistar,
    Nidalee,
    Kindred,
    Zyra,
    DrMundo, // Renamed from Dr.Mundo for valid enum naming
    Shaco,
    Vayne,
    Illaoi,
    Skarner,
    Veigar,
    LeBlanc,
    Rhaast,
    Naafiri,
    Jhin,
    Graves,
    Shyvana,
    Ekko,
    TwistedFate, // Renamed from Twisted Fate for valid enum naming
    Darius,
    Yuumi,
    Fiddlesticks,
    Galio,
    Draven,
    Senna,
    Gragas,
    Varus,
    Mordekaiser,
    JarvanIV, // Renamed from Jarvan IV for valid enum naming
    Elise,
    Rengar,
    Jinx,
    Braum,
    Xayah,
    Leona,
    ChoGath, // Renamed from Cho'Gath for valid enum naming
    Ziggs,
    Zed,
    Vex,
    Zeri,
    Sejuani,
    Aphelios,
    Annie,
    Neeko,
    Brand,
    MissFortune, // Renamed from Miss Fortune for valid enum naming
    Aurora,
    Urgot,
    Kobuko,
    Renekton,
    Garen,
    Viego,
    Samira,
    Zac
}